apiVersion: v1
kind: Pod
metadata:
  name: pod-unico
  labels:
    app: exemplo-simples
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: AMBIENTE
          value: "producao"
        - name: VERSAO
          value: "1.0"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
