apiVersion: v1
kind: Pod
metadata:
  name: pod-comunicacao-localhost
spec:
  containers:
    - name: servidor
      image: hashicorp/http-echo
      args:
        - "-text=olá do servidor"
      ports:
        - containerPort: 5678

    - name: cliente
      image: curlimages/curl
      command: ["sh", "-c", "sleep 5 && curl http://localhost:5678"]
